// apps/weather-react-app/src/app/components/weather-forecast-tile/weather-forecast-tile.tsx
import './weather-forecast-tile.module.scss';
import {roundNumber, titlecase} from "@js-frameworks-weather-app/weather-helpers";
import {ForecastTile} from "@js-frameworks-weather-app/weather-types";

/* eslint-disable-next-line */
export interface WeatherForecastProps {
  tile: ForecastTile
}

export function WeatherForecastTile(props: WeatherForecastProps) {

  const tile = props.tile;

  return (
    <div className="card">
      <div className="card-body">
        <div className="row">
          <h4 className="col-12 text-center">{roundNumber(tile.realTemp)} °C</h4>
          <h5 className="col-12 text-center">Feels like</h5>
          <h4 className="col-12 text-center">{roundNumber(tile.feelsTemp)} °C</h4>
        </div>
        <div className="row">
          <img className="col-12 my-n5 img-fluid text-center" src={tile.weatherIcon}/>
          <h5 className="col-12 mt-1 text-center">{titlecase(tile.weatherTitle)}</h5>
          <div className="col-12 text-center">{titlecase(tile.weatherDescription)}</div>
        </div>
      </div>
    </div>
  );
}

export default WeatherForecastTile;

// apps/weather-angular-app/src/app/components/weather-forecast-tile/weather-forecast-tile.component.ts
import {Component, Input} from '@angular/core';
import {ForecastTile} from "@js-frameworks-weather-app/weather-types";

@Component({
  selector: 'weather-forecast-tile [tile]',
  templateUrl: './weather-forecast-tile.component.html',
  styleUrls: ['./weather-forecast-tile.component.scss'],
})
export class WeatherForecastTileComponent {

  @Input() tile!: ForecastTile;
}

<div class="card">
  <div class="card-body">
    <div class="row">
      <h4 class="col-12 text-center">{{ tile.realTemp | number:'0.0-0' }} °C</h4>
      <h5 class="col-12 text-center">Feels like</h5>
      <h4 class="col-12 text-center">{{ tile.feelsTemp | number:'0.0-0' }} °C</h4>
    </div>
    <div class="row">
      <img class="col-12 my-n5 img-fluid text-center" [src]="tile.weatherIcon"/>
      <h5 class="col-12 mt-1 text-center">{{ tile.weatherTitle | titlecase }}</h5>
      <div class="col-12 text-center">{{ tile.weatherDescription | titlecase }}</div>
    </div>
  </div>
</div>
