// apps/weather-vue-app/src/app/components/weather-forecast/WeatherForecast.vue
<template>
  <div class="row">
    <div class="col">
      <weather-forecast-header @onSubmit="onSubmit($event)"/>
    </div>
  </div>
  <div class="row mt-3" v-if="data$ && cityForecast">
    <div class="col">
      <weather-forecast-body :data$="data$" :cityForecast="cityForecast"/>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue';
import {CityForecast, Forecast} from "@js-frameworks-weather-app/weather-types";
import {Observable} from "rxjs";
import {WeatherForecastApi} from '@js-frameworks-weather-app/weather-services';
import WeatherForecastHeader from "../weather-forecast-header/WeatherForecastHeader.vue";
import WeatherForecastBody from "../weather-forecast-body/WeatherForecastBody.vue";

export default defineComponent({
  components: {
    WeatherForecastHeader,
    WeatherForecastBody
  },
  name: 'WeatherForecast',
  props: {
    tile: {
      type: Object,
      required: true
    }
  },
  data: () => {
    return {
      data$: undefined as Observable<Forecast> | undefined,
      cityForecast: undefined as CityForecast | undefined,
      weatherService: new WeatherForecastApi()
    }
  },
  methods: {
    onSubmit(cityForecast: CityForecast) {
      if (cityForecast.city && cityForecast.forecastType) {
        this.cityForecast = cityForecast;
        this.data$ = this.weatherService.getWeatherForCity(cityForecast);
        this.$router.push({
          name: 'weather-forecast',
          params: {city: cityForecast.city, forecastType: cityForecast.forecastType}
        });
      }
    }
  }
});
</script>

<style scoped lang="scss">

</style>

// apps/weather-react-app/src/app/components/weather-forecast/weather-forecast.tsx
import './weather-forecast.module.scss';
import {CityForecast, Forecast} from "@js-frameworks-weather-app/weather-types";
import {WeatherForecastHeader} from "../weather-forecast-header/weather-forecast-header";
import {WeatherForecastBody} from "../weather-forecast-body/weather-forecast-body";
import {useState} from "react";
import {useNavigate} from 'react-router-dom';
import {Observable} from "rxjs";
import {WeatherForecastApi} from "@js-frameworks-weather-app/weather-services";

/* eslint-disable-next-line */
export interface WeatherForecastProps {
}

export function WeatherForecast(props: WeatherForecastProps) {

  const [data$, setData$] = useState<Observable<Forecast> | undefined>(undefined);
  const [cityForecast, setCityForecast] = useState<CityForecast | undefined>(undefined);

  const navigate = useNavigate();

  const weatherService = new WeatherForecastApi()

  const onSubmit = (cityForecastValue: CityForecast): void => {
    if (cityForecastValue.city && cityForecastValue.forecastType) {
      setCityForecast(cityForecastValue);
      setData$(weatherService.getWeatherForCity(cityForecastValue))
      navigate(`/${cityForecastValue.city}/${cityForecastValue.forecastType}`);
    }
  }

  return (
    <>
      <div className="row">
        <div className="col">
          <WeatherForecastHeader onSubmit={($event) => onSubmit($event)}/>
        </div>
      </div>
      {data$ && cityForecast &&
      <div className="row mt-3">
        <div className="col">
          <WeatherForecastBody data$={data$} cityForecast={cityForecast}/>
        </div>
      </div>
      }
    </>
  );
}

export default WeatherForecast;
