// apps/weather-vue-app/src/app/components/weather-forecast-body/WeatherForecastBody.vue
<template>
  <div class="card">
    <template v-if="data">
      <div class="card-header bg-white" v-if="data.value && cityForecast">
        <h4 class="mt-2">
          {{ cityForecast.city | titlecase }} {{ cityForecast.forecastType | titlecase }} Forecast
          <template v-if="cityForecast.forecastType === 'hourly'">for {{ today | formatDate }}</template>
        </h4>
      </div>

      <div class="card-body">
        <div class="row my-n3">
          <template v-if="data.value && cityForecast">
            <template v-if="data.value | filterForecast(cityForecast.forecastType) as filterdData">
              <template v-if="filterdData.hourly">
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-2" v-for="hour in filterdData.hourly">
                  <weather-forecast-tile :tile="createForecastTile(hour, cityForecast.forecastType)"/>
                </div>
              </template>
              <template v-if="filterdData.daily">
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-2" v-for="day in filterdData.daily">
                  <weather-forecast-tile :tile="createForecastTile(day, cityForecast.forecastType)"/>
                </div>
              </template>
            </template>
          </template>
          <template v-if="!data.loading && !data.value">
            <div class="col">
              <h4 class=" text-center">
                Not Found
              </h4>
            </div>
          </template>
          <template v-if="data.error">
            <div class="col">
              <h4 class=" text-center">
                Error
              </h4>
            </div>
          </template>
          <template v-if="data.loading && !data.error">
            <div class="col">
              <h4 class=" text-center">
                Loading...
              </h4>
            </div>
          </template>
        </div>
      </div>
    </template>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue';
import {AsyncWrapper, Forecast} from "@js-frameworks-weather-app/weather-types";
import WeatherForecastTile from "../weather-forecast-tile/WeatherForecastTile.vue";

export default defineComponent({
  components: {
    WeatherForecastTile
  },
  name: 'WeatherForecastBody',
  props: {
    data$: {
      required: true
    },
    cityForecast: {
      required: true
    }
  },
  data: () => {
    return {
      today: new Date(),
      data: {} as AsyncWrapper<Forecast>
    }
  },
});
</script>

<style scoped lang="scss">

</style>

// apps/weather-angular-app/src/app/components/weather-forecast-body/weather-forecast-body.component.ts
import {Component, Input} from '@angular/core';
import {Observable} from "rxjs";
import {
  CityForecast,
  Daily,
  Forecast,
  ForecastTile,
  ForecastType,
  Hourly
} from "@js-frameworks-weather-app/weather-types";
import {createForecastTile} from "@js-frameworks-weather-app/weather-helpers";


@Component({
  selector: 'weather-forecast-body [data\\$] [cityForecast]',
  templateUrl: './weather-forecast-body.component.html',
  styleUrls: ['./weather-forecast-body.component.scss'],
})
export class WeatherForecastBodyComponent {

  @Input() data$!: Observable<Forecast>;
  @Input() cityForecast!: CityForecast;

  today: Date = new Date();

  createForecastTile(forecast: Hourly | Daily, forecastType: ForecastType): ForecastTile {
    return createForecastTile(forecast, forecastType);
  }
}

<div class="card">
  <ng-container *ngIf="data$ | withStatus | async as data">
    <div class="card-header bg-white" *ngIf="data.value && cityForecast">
      <h4 class="mt-2">
        {{ cityForecast.city | titlecase }} {{ cityForecast.forecastType | titlecase }} Forecast
        <ng-container *ngIf="cityForecast.forecastType === 'hourly'">for {{ today | date }}</ng-container>
      </h4>
    </div>

    <div class="card-body">
      <div class="row my-n3">
        <ng-template [ngIf]="data.value && cityForecast">
          <ng-container *ngIf="data.value | filterForecast:cityForecast.forecastType as filterdData">
            <ng-template [ngIf]="filterdData.hourly">
              <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-2" *ngFor="let hour of filterdData.hourly">
                <weather-forecast-tile
                  [tile]="createForecastTile(hour, cityForecast.forecastType)"></weather-forecast-tile>
              </div>
            </ng-template>
            <ng-template [ngIf]="filterdData.daily">
              <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-2" *ngFor="let day of filterdData.daily">
                <weather-forecast-tile
                  [tile]="createForecastTile(day, cityForecast.forecastType)"></weather-forecast-tile>
              </div>
            </ng-template>
          </ng-container>
        </ng-template>
        <ng-template [ngIf]="!data.loading && !data.value">
          <div class="col">
            <h4 class=" text-center">
              Not Found
            </h4>
          </div>
        </ng-template>
        <ng-template [ngIf]="data.error">
          <div class="col">
            <h4 class=" text-center">
              Error
            </h4>
          </div>
        </ng-template>
        <ng-template [ngIf]="data.loading && !data.error">
          <div class="col">
            <h4 class=" text-center">
              Loading...
            </h4>
          </div>
        </ng-template>
      </div>
    </div>
  </ng-container>
</div>
