// apps/weather-vue-app/src/app/App.vue
<template>
  <div class="container-fluid d-flex justify-content-center mt-4">
    <h1>{{ title }}</h1>
  </div>
  <div class="container mt-3">
    <router-view></router-view>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue';

export default defineComponent({
  name: 'App',
  data: () => {
    return {
      title: 'Weather Forecast (Vue)'
    }
  },
});
</script>

<style lang="scss">

</style>

// apps/weather-react-app/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import AppRouter from "./router/app-router";

export function App() {

  const title = 'Weather Forecast (React)';

  return (
    <>
      <div className="container-fluid d-flex justify-content-center mt-4">
        <h1>{title}</h1>
      </div>
      <div className="container mt-3">
        <AppRouter/>
      </div>
    </>
  );
}

export default App;
