// apps/weather-react-app/src/app/components/weather-forecast-tile/weather-forecast-tile.tsx
import './weather-forecast-tile.module.scss';
import {roundNumber, titlecase} from "@js-frameworks-weather-app/weather-helpers";
import {ForecastTile} from "@js-frameworks-weather-app/weather-types";

/* eslint-disable-next-line */
export interface WeatherForecastProps {
  tile: ForecastTile
}

export function WeatherForecastTile(props: WeatherForecastProps) {

  const tile = props.tile;

  return (
    <div className="card">
      <div className="card-body">
        <div className="row">
          <h4 className="col-12 text-center">{roundNumber(tile.realTemp)} °C</h4>
          <h5 className="col-12 text-center">Feels like</h5>
          <h4 className="col-12 text-center">{roundNumber(tile.feelsTemp)} °C</h4>
        </div>
        <div className="row">
          <img className="col-12 my-n5 img-fluid text-center" src={tile.weatherIcon}/>
          <h5 className="col-12 mt-1 text-center">{titlecase(tile.weatherTitle)}</h5>
          <div className="col-12 text-center">{titlecase(tile.weatherDescription)}</div>
        </div>
      </div>
    </div>
  );
}

export default WeatherForecastTile;

// apps/weather-vue-app/src/app/components/weather-forecast-tile/WeatherForecastTile.vue
<template>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <h4 class="col-12 text-center">{{ tile.realTemp | roundNumber }} °C</h4>
        <h5 class="col-12 text-center">Feels like</h5>
        <h4 class="col-12 text-center">{{ tile.feelsTemp | roundNumber }} °C</h4>
      </div>
      <div class="row">
        <img class="col-12 my-n5 img-fluid text-center" :src="tile.weatherIcon"/>
        <h5 class="col-12 mt-1 text-center">{{ tile.weatherTitle | titlecase }}</h5>
        <div class="col-12 text-center">{{ tile.weatherDescription | titlecase }}</div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue';

export default defineComponent({
  name: 'WeatherForecastTile',
  props: {
    tile: {
      required: true
    }
  },
});
</script>

<style scoped lang="scss">

</style>
